### PR TITLE
Add `getDailyHydration`, `updateHydrationLogOunces`, `getGolfScorecard`, `getGolfSummary`, `updateWeight`, `getHeartRate`, add `ActivityType` filter, and add `put` support

### PR DESCRIPTION
**Pull request by gregegan**
This is a follow up PR to https://github.com/Pythe1337N/garmin-connect/pull/70 so it has those updates in it as well and some small cleanup, I will resolve after that merges

- [x] Add support for `/activities` filtering by activitytype and subactivitytype
- [x] Add in client `put` function
- [x] `getDailyHydration`
- [x] `updateHydrationLogOunces`
- [x] `getGolfScorecard`
- [x] `getGolfSummary`
- [x] `getHeartRate`
- [x] `updateWeight`
- [x] Updated readme

### CODE REVIEW

**Comment by gregegan** [comment]
cc @Pythe1337N @gooin

**Comment by gregegan** [comment]
@Pythe1337N let me know if you plan to do a new version for all of these updates in both pr's and I can update the readme to be `v1.7.0`

**Comment by Pythe1337N** [comment]
I can do that update, but please let me update the version number. It's automated with npm. Just let me know whenever the PR is finished.

**Comment by gregegan** [comment]
Both are finished @Pythe1337N

**Comment by gregegan** [comment]
Can you merge these all @Pythe1337N ?

**Comment by Pythe1337N** [comment]
Yes @gregegan, will do it asap

**Pull request merged**
