### PR TITLE
Implement `getSleepData` ,`getSleepDuration`, `getDailyWeightData`, `getDailyWeight`, `getDailyHydration`

### PR DESCRIPTION
**Pull request by gregegan**
- [x] Update Readme
- [x] Abstract types into individual files since they are large
- [x] add proper error handling to new functions
- [x] implement `getSleepData`
- [x] implement `getSleepDuration`
- [x] implement  `getDailyWeight`
- [x] implement `getDailyWeightData`
- [x] implement `getDailyHydration`

### CODE REVIEW

**Comment by gregegan** [comment]
cc @Pythe1337N

**Comment by gregegan** [comment]
cc @gooin also

**Review by Pythe1337N — APPROVED** [review]

**Comment by Pythe1337N** [comment]
Thanks for your PR, is this ready for a release?

**Comment by gregegan** [comment]
Send it @Pythe1337N! I'll likely be adding in a few other endpoints and some cleanup soon

**Comment by gooin** [comment]
good job

**Comment by gregegan** [comment]
> good job

Thanks!

**Pull request merged**
